// src/lib/game/quest.ts
// Pure quest XP projection — no DB queries, no side effects.
// Accepts a ResolvedDay-shaped input (the page already fetches this).

import type { XpEvent, QuestProjection } from "@/lib/game/types";
import {
  FITNESS_XP,
  CATEGORY_ATTRIBUTE_FALLBACK,
  categoryToAttribute,
  baselineAttributeForTest,
  hikeXp,
} from "@/lib/game/rules";

// Minimal resolved-day shape accepted by projectQuestXp — a subset of ResolvedDay.
// The page passes its already-fetched resolveDay result; quest.ts does NO queries.
export type QuestDayInput = {
  dateKey: string;
  isRestDay: boolean;
  workoutTemplate: { category?: string | null; title?: string | null } | null;
  baselinesDue: string[]; // testNames of baselines due today
  plannedHikeToday?: {
    elevationFt: number;
    packWeightLb: number | null;
  } | null;
  nutritionLogCount?: number; // how many nutrition logs exist for today
};

/**
 * Project the XP a user would earn if they complete today's plan.
 * Pure — no DB, no async. Called with already-fetched resolveDay data.
 *
 * Projection covers deterministic rules only:
 *   - workout.completed (if training day)
 *   - adherence.day
 *   - baseline.logged (for each due test)
 *   - baseline.onTime (for each due test — assume on-time if logging today)
 *   - hike.completed (if planned hike exists)
 *   - nutrition.day (if ≥2 logs, or as a remaining projection if <2)
 *
 * PR/volume XP are excluded (not deterministic pre-training) and exposed
 * as bonusHints by the calling UI layer.
 *
 * @param input  Resolved day data (already fetched by page.tsx)
 * @param allEvents  All XP events generated by the engine (for earnedTodayXp)
 * @returns QuestProjection with projectedXp, earnedXp, complete, bonusHints
 */
export function projectQuestXp(
  input: QuestDayInput,
  allEvents: XpEvent[],
): QuestProjection {
  const todayKey = input.dateKey;

  // ── Earned XP today ────────────────────────────────────────────────────────
  const earnedEvents = earnedTodayXp(allEvents, todayKey);
  const earnedXp = earnedEvents.reduce((sum, e) => sum + e.xp, 0);

  // ── Projected XP (what the user would earn if they complete the plan) ──────
  let projectedXp = 0;

  if (!input.isRestDay && input.workoutTemplate) {
    // workout.completed
    projectedXp += FITNESS_XP.WORKOUT_COMPLETED;
  }

  // adherence.day (every in-plan day)
  projectedXp += FITNESS_XP.ADHERENCE_DAY;

  // baseline.logged + baseline.onTime for each due test
  projectedXp +=
    input.baselinesDue.length * (FITNESS_XP.BASELINE_LOGGED + FITNESS_XP.BASELINE_ON_TIME);

  // hike.completed (if a planned hike exists)
  if (input.plannedHikeToday) {
    projectedXp += hikeXp(
      input.plannedHikeToday.elevationFt,
      input.plannedHikeToday.packWeightLb,
    );
  }

  // nutrition.day: project 5 XP if not yet logged ≥2 items today
  const nutritionLogged = input.nutritionLogCount ?? 0;
  if (nutritionLogged < 2) {
    projectedXp += FITNESS_XP.NUTRITION_DAY;
  }

  // ── Determine bonus hints ─────────────────────────────────────────────────
  const bonusHints: string[] = [];

  if (!input.isRestDay && input.workoutTemplate) {
    const cat = input.workoutTemplate.category ?? null;
    const attr = categoryToAttribute(cat) ?? CATEGORY_ATTRIBUTE_FALLBACK;
    bonusHints.push(`PR chance +${FITNESS_XP.PR_SET} ${attr}`);
  }

  // ── Complete check ────────────────────────────────────────────────────────
  // Today is "complete" if the user has earned at least one event today
  // and the earned XP meets or exceeds the projected amount.
  const complete = earnedEvents.length > 0 && earnedXp >= projectedXp;

  return {
    projectedXp,
    earnedXp,
    earnedEvents,
    complete,
    bonusHints,
  };
}

/**
 * Filter all XP events to only those for today's dateKey.
 * Pure — no side effects.
 */
export function earnedTodayXp(events: XpEvent[], todayKey: string): XpEvent[] {
  return events.filter((e) => e.dateKey === todayKey);
}

// Re-export so callers can get the baseline attribute without importing rules directly
export { baselineAttributeForTest };
