#!/usr/bin/env python3
"""Materialize the roadmap backlog onto GitHub board #8."""
import json, subprocess, sys, os

ROOT = os.path.dirname(os.path.abspath(__file__))
REPO = "jronnomo/workout-planner"
OWNER = "jronnomo"
PROJ_NUM = "8"
PROJ_ID = "PVT_kwHOAZXu284BZVzf"

backlog = json.load(open(f"{ROOT}/coordination/backlog.json"))
F = json.load(open(f"{ROOT}/coordination/field-ids.json"))
log = open(f"{ROOT}/phases/materialize-log.md", "w")
log.write("# Materialize log\n\n| # | Story | Issue | Sprint | item |\n|---|---|---|---|---|\n")

def run(args):
    r = subprocess.run(args, capture_output=True, text=True)
    if r.returncode != 0:
        raise RuntimeError(r.stderr.strip() or r.stdout.strip())
    return r.stdout.strip()

def body_for(s):
    out = [f"**Epic:** {s.get('epic','')} · **Sprint:** {s.get('sprint','')} · "
           f"**Effort:** {s.get('effort','')} · **Priority:** {s.get('priority','')}", ""]
    if s.get("value"): out += [s["value"], ""]
    ac = s.get("acceptanceCriteria") or []
    if ac:
        out.append("## Acceptance criteria")
        out += [f"- {c}" for c in ac]; out.append("")
    tch = s.get("touches") or []
    if tch:
        out.append("## Touches")
        out.append(", ".join(f"`{t}`" for t in tch)); out.append("")
    dep = s.get("dependsOn") or []
    if dep:
        out.append("## Depends on")
        out += [f"- {d}" for d in dep]; out.append("")
    out.append("_Generated by /roadmap. Build with `/feature-dev`._")
    return "\n".join(out)

def setf(item, field, option):
    fid = F[field]["id"]; oid = F[field]["options"][option]
    run(["gh","project","item-edit","--id",item,"--project-id",PROJ_ID,
         "--field-id",fid,"--single-select-option-id",oid])

ok=0; fail=0
for i, s in enumerate(backlog, 1):
    title = s["title"]
    try:
        url = run(["gh","issue","create","-R",REPO,"--title",title,
                   "--body",body_for(s),"--label","roadmap"])
        url = url.splitlines()[-1].strip()
        item = json.loads(run(["gh","project","item-add",PROJ_NUM,"--owner",OWNER,
                               "--url",url,"--format","json"]))["id"]
        setf(item,"Status","Todo")
        if s.get("priority") in F["Priority"]["options"]: setf(item,"Priority",s["priority"])
        if s.get("effort") in F["Effort"]["options"]: setf(item,"Effort",s["effort"])
        if s.get("sprint") in F["Sprint"]["options"]: setf(item,"Sprint",s["sprint"])
        num = url.rsplit("/",1)[-1]
        log.write(f"| {i} | {title[:60]} | #{num} | {s.get('sprint','')} | ok |\n"); log.flush()
        print(f"[{i}/39] #{num} {title[:50]}")
        ok+=1
    except Exception as e:
        log.write(f"| {i} | {title[:60]} | FAIL | {s.get('sprint','')} | {str(e)[:60]} |\n"); log.flush()
        print(f"[{i}/39] FAIL {title[:50]}: {e}", file=sys.stderr)
        fail+=1

log.write(f"\n**{ok} created, {fail} failed.**\n"); log.close()
print(f"\nDONE: {ok} created, {fail} failed.")
